# 第一阶段：构建前端应用
FROM node:18 AS build-stage
WORKDIR /app
RUN npm config set registry http://registry.npmmirror.com
RUN npm install -g pnpm@8.1.0
COPY package*.json ./
RUN pnpm install
COPY . .
RUN pnpm run build:pro

# 第二阶段：构建后端应用
FROM node:18 AS server-stage
WORKDIR /app
COPY --from=build-stage /app/package*.json ./
RUN pnpm install --production
COPY --from=build-stage /app/express ./express
CMD ["pnpm", "run", "start:express"]

# 第三阶段：基于Caddy构建
FROM caddy:2-alpine
COPY --from=build-stage /app/dist-pro /usr/share/caddy  # 复制前端构建的文件
COPY --from=server-stage /app/express /app/express  # 复制后端应用
COPY /docker/Caddyfile /etc/caddy/Caddyfile

CMD ["caddy", "run"]
