version: '3.8'
services:
  file-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fileencode
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - file-db-data:/var/lib/mysql

  file-dev:
    build:
      context: ..  # 更改此处
      dockerfile: docker/Dockerfile.dev  # 更改此处
    ports:
      - '3005:3005'
      - '3006:3006'
    volumes:
      - /path/to/cert.pem:/etc/caddy/ssl/domain-chain.pem
      - /path/to/key.pem:/etc/caddy/ssl/private.key

volumes:
  file-db-data:
