FROM node:18
WORKDIR /app
RUN npm config set registry http://registry.npmmirror.com
RUN npm install -g pnpm@8.1.0
COPY package*.json ./
RUN pnpm install
COPY . .
RUN pnpm run dev

# 基于 Caddy 构建
FROM caddy:2-alpine
COPY /docker/Caddyfile /etc/caddy/Caddyfile
COPY --from=build-stage /app/dist /usr/share/caddy
