# 基于 Node.js 构建前端应用
FROM node:18 as build-stage
WORKDIR /app
COPY package*.json ./
RUN pnpm install
COPY . .
RUN pnpm run build:pro

# 基于 Caddy 构建
FROM caddy:2-alpine
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build-stage /app/dist /usr/share/caddy
