# Dockerfile-app
FROM node:18

WORKDIR /app

COPY package.json .
RUN npm config set registry http://registry.npmmirror.com
RUN npm install -g pnpm@8.1.0
RUN chmod -R 755 /app
RUN pnpm install

COPY . .

RUN cd /app/cpp && g++ -o AES_CBC AES_CBC.cpp -lssl -lcrypto

EXPOSE 8080

CMD [ "pnpm", "run", "dev" ]
