version: '3'
services:
  db:
    container_name: file-db
    build:
      context: ..
      dockerfile: docker/Dockerfile-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    container_name: file-app
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile-app
    ports:
      - "3006:3006"
      - "8080:3005"
    volumes:
      - /home/hznuoj/vue-element-plus-admin/express:/app/express
      - /home/hznuoj/vue-element-plus-admin/src:/app/src
    restart: always

volumes:
  db_data:
